<?php
$services = [
 ['slug'=>'breast-cancer','title'=>'Breast Cancer Surgery','short'=>'Comprehensive surgical care with a focus on oncological precision, breast preservation when appropriate and recovery.','icon'=>'✚'],
 ['slug'=>'gastrointestinal-cancer','title'=>'Gastrointestinal & Hepatobiliary Cancer Surgery','short'=>'Advanced surgery for stomach, esophagus, liver, pancreas, gallbladder, bile ducts and intestinal cancers.','icon'=>'◈'],
 ['slug'=>'thoracic-cancer','title'=>'Thoracic Cancer Surgery','short'=>'Specialized surgical treatment for lung, chest wall, mediastinal and other thoracic cancers.','icon'=>'◉'],
 ['slug'=>'ovarian-cancer','title'=>'Ovarian Cancer Surgery','short'=>'Comprehensive surgical management for ovarian cancer with individualized treatment planning.','icon'=>'✦'],
 ['slug'=>'gynecologic-cancer','title'=>'Gynecologic Cancer Surgery','short'=>'Surgical care for cancers of the uterus, cervix, ovaries, vulva and related reproductive organs.','icon'=>'◌'],
 ['slug'=>'head-neck-cancer','title'=>'Head & Neck Cancer Surgery','short'=>'Precision surgical treatment for oral, thyroid, salivary gland and other head and neck cancers.','icon'=>'⌁'],
 ['slug'=>'colorectal-cancer','title'=>'Colorectal Cancer Surgery','short'=>'Evidence-based surgical treatment for colon and rectal cancers, including minimally invasive options.','icon'=>'▦'],
 ['slug'=>'pancreatic-cancer','title'=>'Pancreatic Cancer Surgery','short'=>'Specialized management of pancreatic tumors using modern oncological surgical principles.','icon'=>'◆'],
 ['slug'=>'laparoscopic-surgery','title'=>'Laparoscopic Cancer Surgery','short'=>'Minimally invasive surgery designed around smaller incisions, reduced pain and faster recovery.','icon'=>'⌬'],
 ['slug'=>'robotic-surgery','title'=>'Robotic Cancer Surgery','short'=>'Robot-assisted surgery for selected cancers where enhanced visualization and precision are appropriate.','icon'=>'✥'],
 ['slug'=>'palliative-surgery','title'=>'Palliative Surgery','short'=>'Procedures focused on symptom relief, comfort and quality of life during cancer treatment.','icon'=>'♡'],
 ['slug'=>'port-insertion','title'=>'Port Insertion & Day-Care Oncology Procedures','short'=>'Safe chemoport insertion and selected day-care oncology procedures with patient comfort in mind.','icon'=>'＋'],
 ['slug'=>'reconstructive-surgery','title'=>'Reconstructive & Microvascular Surgery','short'=>'Reconstructive procedures intended to restore function, form and confidence following cancer surgery.','icon'=>'◇'],
 ['slug'=>'hipec-pipac','title'=>'Sarcoma & Peritoneal Surface Malignancy Management (HIPEC, PIPAC)','short'=>'Specialized management pathways for selected sarcoma and peritoneal surface malignancies.','icon'=>'◎'],
];

$serviceDetails = [
'breast-cancer'=>['intro'=>'Breast cancer surgery is planned around the type and stage of disease, the patient’s anatomy and the wider treatment plan. Surgical options can include breast-conserving procedures, mastectomy, lymph-node procedures and oncoplastic techniques when appropriate.','points'=>['Early diagnosis and precise staging','Personalized surgical planning','Breast conservation when medically appropriate','Multidisciplinary treatment coordination'],'faqs'=>['What are the common types of breast cancer surgery?','Can breast conservation be considered?','How is recovery planned after surgery?']],
'gastrointestinal-cancer'=>['intro'=>'Gastrointestinal and hepatobiliary cancer surgery covers malignancies involving the esophagus, stomach, liver, gallbladder, bile ducts, pancreas and bowel. The approach is selected according to disease extent and the patient’s overall treatment pathway.','points'=>['Accurate staging and treatment planning','Advanced open and minimally invasive techniques','Organ preservation when feasible','Multidisciplinary cancer care'],'faqs'=>['Which cancers fall under GI and hepatobiliary surgery?','Can minimally invasive surgery be used?','Will additional treatment be needed after surgery?']],
'thoracic-cancer'=>['intro'=>'Thoracic oncology surgery addresses selected cancers of the lung, chest wall and mediastinal structures. Surgical planning is based on imaging, pathology, disease stage and the patient’s overall fitness.','points'=>['Stage-specific surgical planning','Minimally invasive options for selected cases','Careful lymph-node assessment','Coordinated oncology follow-up'],'faqs'=>['Which thoracic cancers may require surgery?','When can minimally invasive surgery be considered?','What does recovery involve?']],
'ovarian-cancer'=>['intro'=>'Ovarian cancer surgery can form an important part of treatment for selected patients. The surgical plan is individualized around disease distribution, pathology and the broader oncology strategy.','points'=>['Comprehensive disease assessment','Individualized cytoreductive planning','Coordination with medical oncology','Recovery and supportive-care planning'],'faqs'=>['How is ovarian cancer surgery planned?','What is cytoreductive surgery?','Can surgery be combined with other treatments?']],
'gynecologic-cancer'=>['intro'=>'Gynecologic oncology surgery includes selected cancers of the uterus, cervix, ovaries, vulva and related structures. Treatment is tailored to diagnosis, stage, fertility considerations where relevant and overall health.','points'=>['Individualized staging and planning','Appropriate minimally invasive techniques','Oncological safety first','Coordinated follow-up care'],'faqs'=>['Which gynecologic cancers may need surgery?','Is minimally invasive surgery always possible?','How is recovery monitored?']],
'head-neck-cancer'=>['intro'=>'Head and neck cancer surgery requires careful planning to balance complete tumour treatment with preservation of speech, swallowing, appearance and function wherever possible.','points'=>['Detailed anatomical assessment','Precision tumour removal','Functional and reconstructive planning','Multidisciplinary support'],'faqs'=>['What cancers are included in head and neck surgery?','How is function preserved?','When is reconstruction considered?']],
'colorectal-cancer'=>['intro'=>'Colorectal cancer surgery is planned according to tumour location, stage, pathology and the wider treatment plan. Minimally invasive approaches may be considered for selected patients.','points'=>['Complete oncological resection','Minimally invasive options when suitable','Careful lymph-node assessment','Recovery-focused perioperative care'],'faqs'=>['What operations are used for colorectal cancer?','Can laparoscopic surgery be used?','What affects recovery time?']],
'pancreatic-cancer'=>['intro'=>'Pancreatic cancer surgery is complex and requires detailed imaging, staging and multidisciplinary planning. The appropriate operation depends on tumour location, resectability and overall patient factors.','points'=>['Detailed imaging and staging','Resectability assessment','Specialist surgical planning','Multidisciplinary cancer care'],'faqs'=>['When is pancreatic surgery considered?','What determines the type of operation?','Why is multidisciplinary planning important?']],
'laparoscopic-surgery'=>['intro'=>'Laparoscopic cancer surgery uses small incisions and a camera-assisted approach for selected operations. The goal is to maintain sound oncological principles while supporting recovery.','points'=>['Smaller incisions for selected procedures','Potentially less postoperative discomfort','Earlier mobilisation for appropriate patients','Shorter hospital stay in selected cases'],'faqs'=>['What is laparoscopic cancer surgery?','Is it suitable for every cancer?','What are the recovery advantages?']],
'robotic-surgery'=>['intro'=>'Robotic cancer surgery can provide enhanced visualization, instrument articulation and precision for selected procedures. Technology is used as a surgical tool within an overall oncological strategy.','points'=>['Enhanced visualization','Fine instrument control','Selected minimally invasive procedures','Recovery-focused care'],'faqs'=>['What is robotic cancer surgery?','Does robotic surgery replace surgical expertise?','Is robotic surgery suitable for every patient?']],
'palliative-surgery'=>['intro'=>'Palliative surgery focuses on relieving symptoms and improving comfort when an operation can provide meaningful quality-of-life benefit. The decision is individualized and balanced against risks and alternatives.','points'=>['Symptom-focused planning','Individual risk-benefit assessment','Coordination with oncology and supportive care','Comfort and quality of life'],'faqs'=>['What is the goal of palliative surgery?','How is benefit assessed?','Can palliative surgery be combined with other care?']],
'port-insertion'=>['intro'=>'Implantable venous access ports can provide reliable access for selected patients receiving systemic cancer treatment. Day-care procedures are planned with attention to safety, comfort and aftercare.','points'=>['Planned venous access','Day-care procedure pathways','Sterile procedural technique','Clear aftercare instructions'],'faqs'=>['What is a chemoport?','How long does port insertion take?','What care is needed after insertion?']],
'reconstructive-surgery'=>['intro'=>'Reconstructive and microvascular surgery can help restore function and form after selected cancer operations. Planning considers the original tumour site, treatment history and individual goals.','points'=>['Functional reconstruction','Restoration of form where possible','Microvascular techniques for selected cases','Coordinated rehabilitation'],'faqs'=>['Why is reconstruction considered after cancer surgery?','What does microvascular surgery involve?','How is reconstruction planned?']],
'hipec-pipac'=>['intro'=>'HIPEC and PIPAC are specialized approaches used for carefully selected patients with peritoneal surface malignancies. Suitability depends on disease distribution, tumour biology, previous treatment and overall condition.','points'=>['Detailed disease mapping','Multidisciplinary case selection','Cytoreductive surgery pathways where appropriate','Specialist intraperitoneal treatment options'],'faqs'=>['What is HIPEC?','What is PIPAC?','Who may be considered for these treatments?']],
];

$blogs = [
 ['slug'=>'consultation-guide','date'=>'02 July 2026','title'=>'Understanding Advanced Breast Cancer Surgery','tag'=>'Breast Oncology','img'=>'blogs-reference.jpg','text'=>'A practical overview of how surgical planning can vary with stage, tumour biology and the wider treatment plan.'],
 ['slug'=>'minimally-invasive','date'=>'28 June 2026','title'=>'Breast Conservation: When Is It Considered?','tag'=>'Patient Guide','img'=>'doctor-reference.jpg','text'=>'Understanding the principles behind breast-conserving surgery and individualized treatment decisions.'],
 ['slug'=>'recovery-guide','date'=>'15 June 2026','title'=>'Understanding Colorectal Cancer & Surgical Treatment','tag'=>'Colorectal','img'=>'services-reference.jpg','text'=>'Key questions patients can discuss with their cancer team when surgery becomes part of the treatment pathway.'],
];
