</main>
<footer class="site-footer"><div class="container footer-grid">
<div class="footer-brand"><img src="<?=$basePath?>assets/images/arjun-verma-clinic-logo.png" alt="Dr. Arjun Verma"><p>A premium surgical oncology practice experience centred on precision, appropriate technology, clear communication and patient dignity.</p><div class="socials"><a href="<?=$basePath?>contact.php" aria-label="Contact">↗</a><a href="<?=$basePath?>contact.php" aria-label="Book appointment">＋</a><a href="<?=$basePath?>contact.php" aria-label="Request consultation">✦</a></div></div>
<div><h4>Explore</h4><a href="<?=$basePath?>about.php">About Dr. Verma</a><a href="<?=$basePath?>services.php">All Specialities</a><a href="<?=$basePath?>locations.php">Consulting Locations</a><a href="<?=$basePath?>reviews.php">Patient Feedback</a><a href="<?=$basePath?>blogs.php">Health Journal</a><a href="<?=$basePath?>contact.php">Contact</a></div>
<div><h4>Specialities</h4><?php foreach(array_slice($services,0,7) as $s): ?><a href="<?=$basePath?>services/<?=$s['slug']?>.php"><?=htmlspecialchars($s['title'])?></a><?php endforeach; ?><a href="<?=$basePath?>services.php" class="footer-action">Explore all 14 ↗</a></div>
<div><h4>Appointments</h4><p class="footer-note">Use the consultation page to request an appointment, share your requirements and ask about the appropriate next step.</p><a href="<?=$basePath?>contact.php" class="footer-action">Request a consultation ↗</a><div class="footer-mini"><span>PRIVATE &amp; CONFIDENTIAL</span><span>BY ENQUIRY</span></div></div>
</div><div class="container footer-bottom"><span>© <?=date('Y')?> Dr. Arjun Verma. All Rights Reserved.</span><span>Surgical Oncology • Laparoscopic • Robotic</span></div></footer>
<button class="back-top" id="backTop" aria-label="Back to top">↑</button><a class="floating-whatsapp" href="<?=$basePath?>contact.php" aria-label="Request a consultation">✆</a>
<script src="<?=$basePath?>assets/js/main.js" defer></script><script src="<?=$basePath?>assets/js/animations.js" defer></script></body></html>
